config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  
  get 'boy', to: "home#boy"
  get 'girl', to: "home#girl"
  get 'friend', to: "home#friend"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def boy
    @show_love = true
  end

  def girl
    @show_love = false
  end

  def friend
    @show_love = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_love.html.erb
<h1>SHOW YOU MY LOVE</h1>

app/views/home/boy.html.erb
<h1>boys</h1>

app/views/home/friend.html.erb
<h1>friends</h1>

app/views/home/girl.html.erb
<h1>girls</h1>

app/views/home/index.html.erb
<h1>Homepage</h1>
<%= link_to "boys", boy_path, class: "btn btn-primary" %>
<%= link_to "girls", girl_path, class: "btn btn-primary" %>
<%= link_to "friends", friend_path, class: "btn btn-primary" %>

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "ocean1.JPG" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "ocean2.JPG" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "ocean3.JPG" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgressBar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @show_love %>
      <%= render partial: 'love' %>
    <% end %>

    <%= yield %>
  </body>
</html>